name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_requests:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu -latest
  strategy:
    matrix:
      python-versions: [3.6, 3.7, 3.8]
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_versions }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run Tests
      run: |
        pytest
      end:
        PYTHONPATH: .